// src/renderer/components/ChordIntervals/ChordIntervals.tsx
import React, { useMemo } from 'react';

import { ChordIntervalsProps } from './types';
import { INTERVALS, getPlayedIntervals, isIncludedAs } from './utils';

const PLAYED_HEIGHT_MAP: Record<number, string> = {
  0: 'h-[50%]',
  1: 'h-[60%]',
  2: 'h-[70%]',
  3: 'h-[80%]',
  4: 'h-[90%]',
};

export const ChordIntervals: React.FC<ChordIntervalsProps> = ({
  className,
  intervals,
  targets,
  pitchClasses,
  tonic,
  quizMode,
}) => {
  const played = useMemo(
    () => getPlayedIntervals(tonic, pitchClasses || []),
    [tonic, pitchClasses]
  );

  const hasTargets = targets && targets.length;

  return (
    <div className={`flex items-center h-[6em] ${className ?? ''}`}>
      {INTERVALS.BASE.map((i, index) => {
        const activeAs = intervals && isIncludedAs(i, intervals);
        const targetAs = targets && isIncludedAs(i, targets);

        const isPlayed = played[index];
        const playedLevel = Math.min(4, isPlayed);

        let bgColor = 'bg-[#5c5c5c]';

        if (activeAs || targetAs) {
          if (hasTargets) {
            if (targetAs && (activeAs || isPlayed)) {
              bgColor = 'bg-[#127c4f]';
            } else if (targetAs) {
              bgColor = quizMode ? 'bg-[#5c5c5c]' : 'bg-[#3567f0]';
            } else if (activeAs) {
              bgColor = 'bg-[#3567f0]';
            } else if (isPlayed) {
              bgColor = 'bg-[#ac2426]';
            }
          } else {
            bgColor = 'bg-[#3567f0]';
          }
        } else if (isPlayed) {
          bgColor = hasTargets ? 'bg-[#ac2426]' : 'bg-[#3567f0]';
        }

        const heightClass = PLAYED_HEIGHT_MAP[playedLevel] || 'h-[50%]';

        return (
          <div
            className={`flex flex-col text-center items-center justify-center w-[2.5em] text-[0.8em] ${heightClass} bg-[#303030] transition-[height] duration-200 leading-[1em] gap-y-[0.5em] ${bgColor} ${
              activeAs || targetAs ? 'font-bold' : ''
            }`}
            key={i}
          >
            {activeAs || targetAs ? (
              <span>{activeAs || targetAs}</span>
            ) : (
              [<span key="0">{i}</span>, <span key="1">{INTERVALS.OCTAVE[index]}</span>]
            )}
          </div>
        );
      })}
    </div>
  );
};

ChordIntervals.defaultProps = {
  className: undefined,
  intervals: [],
  targets: [],
  pitchClasses: [],
  tonic: null,
  quizMode: false,
};

export default ChordIntervals;

// src/components/ChordIntervals/ChordIntervals.vue
<template>
  <div class="w-full">
    <div class="grid grid-cols-6 gap-1.5" role="list" :aria-label="ariaLabel">
      <div v-for="(label, index) in BASE_LABELS" :key="label" role="listitem">
        <div
          class="card"
          :class="
            activeAsMap[index] || targetAsMap[index]
              ? 'bg-info '
              : 'bg-base-200 '
          "
        >
          <div class="card-body">
            <div
              class="text-center font-bold"
              :class="
                activeAsMap[index] || targetAsMap[index]
                  ? ' text-info-content'
                  : 'text-base-content'
              "
            >
              {{ label }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import {
  INTERVALS,
  BASE_LABELS,
  isIncludedAs,
  getPlayedIntervals,
} from "./utils";

export interface ChordIntervalsProps {
  className?: string;
  intervals?: string[];
  targets?: string[];
  pitchClasses?: string[];
  tonic?: string | null;
  quizMode?: boolean;
}

const props = withDefaults(defineProps<ChordIntervalsProps>(), {
  className: "",
  intervals: () => [],
  targets: () => [],
  pitchClasses: () => [],
  tonic: null,
  quizMode: false,
});

const { t } = useI18n();

const ariaLabel = computed(() => t("chordIntervals.label", { count: 12 }));

/** 从 intervals prop 推导的活跃音程映射 */
const activeFromIntervals = computed(() =>
  INTERVALS.BASE.map((i) => isIncludedAs(i, props.intervals)),
);

/** 从 pitchClasses + tonic 回退推导的活跃音程映射（当 intervals 为空时使用） */
const activeFromPitchClasses = computed(() => {
  if (props.intervals.length > 0) return Array(12).fill(null);
  const played = getPlayedIntervals(props.tonic, props.pitchClasses);
  return played.map((count) => (count > 0 ? true : null));
});

const activeAsMap = computed(() =>
  INTERVALS.BASE.map(
    (_, index) =>
      activeFromIntervals.value[index] || activeFromPitchClasses.value[index],
  ),
);

const targetAsMap = computed(() =>
  INTERVALS.BASE.map((i) => isIncludedAs(i, props.targets)),
);
</script>
