// src/views/ChordDictionary/ChordDictionaryToolbar.vue
<template>
  <div
    class="chord-dictionary-toolbar flex flex-col gap-2 px-4 py-2 border-b border-base-300 flex-shrink-0"
  >
    <!-- Row 1: Search + controls -->
    <div class="flex items-center gap-2">
      <!-- Hamburger for mobile drawer -->
      <button
        v-if="showDrawerToggle"
        class="btn btn-sm btn-ghost btn-square lg:hidden"
        :aria-label="t('common.openSidebar')"
        @click="$emit('toggleDrawer')"
      >
        <Icon name="menu" :size="18" />
      </button>

      <!-- Inline search -->
      <ChordSearch :on-select="handleChordSelect" mode="inline" />

      <template v-if="!disableUpdate">
        <!-- Group by dropdown -->
        <div class="relative hidden sm:block">
          <button
            class="btn btn-sm btn-outline gap-1"
            @click="menuOpen = !menuOpen"
          >
            <span class="truncate max-w-[80px]">
              {{ getGroupLabel(groupBy) }}
            </span>
            <Icon name="chevron-down" size="14" />
          </button>

          <div
            v-show="menuOpen"
            class="absolute top-full left-0 z-dropdown mt-1 card bg-base-100 shadow-md min-w-[180px]"
          >
            <ul class="menu bg-base-100 w-full p-1">
              <li class="menu-title">
                <span>{{ t("chordDictionary.group") }}</span>
              </li>
              <li>
                <a
                  :class="{ 'bg-primary/10 text-primary': groupBy === 'none' }"
                  @click="
                    updateGroupBy('none');
                    menuOpen = false;
                  "
                >
                  {{ t("chordDictionary.groupNames.noGroup") }}
                </a>
              </li>
              <li>
                <a
                  :class="{
                    'bg-primary/10 text-primary': groupBy === 'quality',
                  }"
                  @click="
                    updateGroupBy('quality');
                    menuOpen = false;
                  "
                >
                  {{ t("chordDictionary.groupNames.byQuality") }}
                </a>
              </li>
              <li>
                <a
                  :class="{
                    'bg-primary/10 text-primary': groupBy === 'intervals',
                  }"
                  @click="
                    updateGroupBy('intervals');
                    menuOpen = false;
                  "
                >
                  {{ t("chordDictionary.groupNames.byIntervals") }}
                </a>
              </li>
            </ul>
          </div>
          <div
            v-show="menuOpen"
            class="fixed inset-0 z-overlay"
            @click="menuOpen = false"
          ></div>
        </div>

        <!-- Filter toggles -->
        <div class="hidden md:flex items-center gap-3 ml-1">
          <label
            class="flex items-center gap-1.5 cursor-pointer text-xs text-base-content/70 whitespace-nowrap"
          >
            <input
              type="checkbox"
              class="toggle toggle-xs toggle-primary"
              :checked="hideDisabled"
              @change="toggleHideDisabled"
            />
            {{ t("chordDictionary.hideDisabledChords") }}
          </label>
        </div>
      </template>

      <div class="flex-1"></div>

      <div v-if="!disableUpdate" class="join">
        <button
          class="btn btn-xs join-item"
          :class="
            interactiveMode === 'detect'
              ? 'btn-primary'
              : 'btn-ghost text-base-content/70'
          "
          :title="t('chordDictionary.detect')"
          :aria-label="t('chordDictionary.detect')"
          :aria-pressed="interactiveMode === 'detect'"
          @click="handleToggleInteractive('detect')"
        >
          <Icon name="eye" :size="14" />
        </button>
        <button
          class="btn btn-xs join-item"
          :class="
            interactiveMode === 'play'
              ? 'btn-primary'
              : 'btn-ghost text-base-content/70'
          "
          :title="t('chordDictionary.play')"
          :aria-label="t('chordDictionary.play')"
          :aria-pressed="interactiveMode === 'play'"
          @click="handleToggleInteractive('play')"
        >
          <Icon name="controller" :size="14" />
        </button>
      </div>

      <SettingsButton
        :aria-label="t('chordDictionary.openDictionarySettings')"
        @click="settingsOpen = true"
      />

      <SettingsDrawer
        v-model="settingsOpen"
        :title="t('chordDictionary.settings')"
      >
        <ChordDictionarySettings />
      </SettingsDrawer>
    </div>

    <!-- Row 2: Chroma selector auto-fit grid -->
    <div
      class="grid gap-1"
      style="grid-template-columns: repeat(auto-fit, minmax(2.5rem, 1fr))"
      role="tablist"
      :aria-label="t('chordDictionary.chromaNavigation')"
    >
      <button
        v-for="note in notesList"
        :key="note"
        role="tab"
        :aria-selected="selectedChroma === getChroma(note)"
        class="btn btn-xs sm:btn-sm px-0 min-h-0 h-7 sm:h-8 text-xs font-medium"
        :class="
          selectedChroma === getChroma(note)
            ? 'btn-primary'
            : 'btn-ghost hover:bg-base-200'
        "
        @click="$emit('selectChroma', getChroma(note))"
      >
        {{ formatNote(note) }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import { Note } from "tonal";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { useSettingsStore } from "@/stores/settings";
import type { KeySignatureConfig } from "@/helpers";
import {
  NOTE_NAMES,
  formatSharpsFlats,
  getNoteInKeySignature,
} from "@/helpers";
import { SettingsButton } from "@/components/SettingsButton";
import { SettingsDrawer } from "@/components/SettingsDrawer/";
import Icon from "@/components/Icon/Icon.vue";
import ChordSearch from "./ChordSearch/ChordSearch.vue";
import ChordDictionarySettings from "../Settings/ChordDictionarySettings/ChordDictionarySettings.vue";

interface Props {
  disableUpdate?: boolean;
  showDrawerToggle?: boolean;
  keySignature: KeySignatureConfig;
  selectedChroma: number | null;
}

const props = withDefaults(defineProps<Props>(), {
  disableUpdate: false,
  showDrawerToggle: false,
});

defineEmits<{
  (e: "toggleDrawer"): void;
  (e: "selectChroma", chroma: number): void;
}>();

const { t } = useI18n();
const router = useRouter();
const settingsStore = useSettingsStore();

const settingsOpen = ref(false);
const menuOpen = ref(false);

const groupBy = computed(() => settingsStore.settings.chordDictionary.groupBy);
const hideDisabled = computed(
  () => settingsStore.settings.chordDictionary.hideDisabled,
);
const interactiveMode = computed(
  () => settingsStore.settings.chordDictionary.interactive,
);

// Chroma selector
const notesList = computed(() => NOTE_NAMES);

function getChroma(note: string): number {
  return Note.chroma(note) as number;
}

function formatNote(note: string): string {
  return formatSharpsFlats(
    getNoteInKeySignature(note, props.keySignature.notes),
  );
}

function getGroupLabel(groupByValue: string): string {
  if (groupByValue === "none") return t("chordDictionary.groupNames.noGroup");
  if (groupByValue === "quality")
    return t("chordDictionary.groupNames.byQuality");
  return t("chordDictionary.groupNames.byIntervals");
}

function toggleHideDisabled() {
  settingsStore.updateSetting(
    "chordDictionary.hideDisabled",
    !hideDisabled.value,
  );
}

function handleToggleInteractive(value: string) {
  settingsStore.updateSetting("chordDictionary.interactive", value);
}

function updateGroupBy(value: "none" | "quality" | "intervals") {
  settingsStore.updateSetting("chordDictionary.groupBy", value);
}

function handleChordSelect(chord: string | null) {
  if (chord) {
    router.push({
      path: `/chord-dictionary/${encodeURIComponent(chord)}`,
    });
  }
}
</script>

// src/renderer/views/ChordDictionary/ChordDictionaryToolbar.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';

import { useSettings } from 'renderer/contexts/Settings';
import { Icon } from 'renderer/components';

import { ChordDictionarySettings as TChordDictionarySettings } from 'main/types';
import { ChordSearch } from './ChordSearch';
import ChordDictionarySettings from '../Settings/ChordDictionarySettings';

type Props = {
  disableUpdate?: boolean;
};

const ChordDictionaryToolbar: React.FC<Props> = ({ disableUpdate }) => {
  const navigate = useNavigate();
  const { settings, updateSetting } = useSettings();
  const { t } = useTranslation();

  const [settingsOpen, setSettingsOpen] = useState<boolean>(false);

  const toggleHideDisabled = () =>
    updateSetting('chordDictionary.hideDisabled', !settings.chordDictionary.hideDisabled);
  const toggleFilterInKey = () =>
    updateSetting('chordDictionary.filterInKey', !settings.chordDictionary.filterInKey);

  const handleToggleInteractive = (interactive: TChordDictionarySettings['interactive']) => () =>
    updateSetting('chordDictionary.interactive', interactive);

  const getGroupLabel = (groupBy: string) => {
    if (groupBy === 'none') return t('chordDictionary.groupNames.noGroup');
    if (groupBy === 'quality') return t('chordDictionary.groupNames.byQuality');
    return t('chordDictionary.groupNames.byIntervals');
  };

  const handleChordSelect = (chord: string | null) => {
    if (chord) {
      navigate(`./${encodeURIComponent(chord)}`);
    }
  };

  const handleSettingsClosed = () => {
    setSettingsOpen(false);
  };

  return (
    <>
      <div className="flex items-center gap-3 py-3 px-4 border-b border-neutral-300">
        {!disableUpdate && (
          <div className="dropdown dropdown-bottom">
            <button type="button" tabIndex={0} className="btn btn-neutral gap-2">
              {`${getGroupLabel(settings.chordDictionary.groupBy)}${
                settings.chordDictionary.filterInKey ? t('chordDictionary.inKey') : ''
              }`}
              <Icon name="angle-down" />
            </button>
            <ul
              tabIndex={0}
              role="menu"
              className="dropdown-content z-[1] menu p-3 shadow-lg bg-base-100 rounded-box w-64"
            >
              <li>
                <div className="menu-title px-2 py-1">{t('chordDictionary.group')}</div>
                <ul role="none">
                  <li>
                    <label className="label cursor-pointer gap-2">
                      <span>
                        <input
                          id="groupByNone"
                          type="radio"
                          name="group"
                          className="radio radio-sm"
                          checked={settings.chordDictionary.groupBy === 'none'}
                          onChange={() => updateSetting('chordDictionary.groupBy', 'none')}
                        />
                      </span>
                      <label htmlFor="groupByNone">{t('chordDictionary.groupNames.noGroup')}</label>
                    </label>
                  </li>
                  <li>
                    <label className="label cursor-pointer gap-2">
                      <span>
                        <input
                          id="groupByQuality"
                          type="radio"
                          name="group"
                          className="radio radio-sm"
                          checked={settings.chordDictionary.groupBy === 'quality'}
                          onChange={() => updateSetting('chordDictionary.groupBy', 'quality')}
                        />
                      </span>
                      <label htmlFor="groupByQuality">
                        {t('chordDictionary.groupNames.byQuality')}
                      </label>
                    </label>
                  </li>
                  <li>
                    <label className="label cursor-pointer gap-2">
                      <span>
                        <input
                          id="groupByIntervals"
                          type="radio"
                          name="group"
                          className="radio radio-sm"
                          checked={settings.chordDictionary.groupBy === 'intervals'}
                          onChange={() => updateSetting('chordDictionary.groupBy', 'intervals')}
                        />
                      </span>
                      <label htmlFor="groupByIntervals">
                        {t('chordDictionary.groupNames.byIntervals')}
                      </label>
                    </label>
                  </li>
                </ul>
              </li>
              <div className="divider my-1" />
              <li>
                <div className="menu-title px-2 py-1">{t('chordDictionary.filter')}</div>
                <ul role="none">
                  <li>
                    <label className="label cursor-pointer gap-2">
                      <span>
                        <input
                          id="hideDisabled"
                          type="checkbox"
                          className="checkbox checkbox-sm"
                          checked={settings.chordDictionary.hideDisabled}
                          onChange={toggleHideDisabled}
                        />
                      </span>
                      <label htmlFor="hideDisabled">
                        {t('chordDictionary.hideDisabledChords')}
                      </label>
                    </label>
                  </li>
                  <li>
                    <label className="label cursor-pointer gap-2">
                      <span>
                        <input
                          id="filterInKey"
                          type="checkbox"
                          className="checkbox checkbox-sm"
                          checked={settings.chordDictionary.filterInKey}
                          onChange={toggleFilterInKey}
                        />
                      </span>
                      <label htmlFor="filterInKey">{t('chordDictionary.onlyChordsInKey')}</label>
                    </label>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        )}
        <div className="divider divider-horizontal" />
        <ChordSearch onSelect={handleChordSelect} />
        {!disableUpdate && (
          <div role="group" className="btn-group gap-1">
            <button
              type="button"
              className={`btn btn-sm ${
                settings.chordDictionary.interactive === 'detect' ? 'btn-active' : ''
              }`}
              onClick={handleToggleInteractive('detect')}
            >
              {t('chordDictionary.detect')}
            </button>
            <button
              type="button"
              className={`btn btn-sm ${
                settings.chordDictionary.interactive === 'play' ? 'btn-active' : ''
              }`}
              onClick={handleToggleInteractive('play')}
            >
              {t('chordDictionary.play')}
            </button>
          </div>
        )}
        <button
          type="button"
          className="btn btn-neutral btn-square btn-sm"
          onClick={() => setSettingsOpen(true)}
          aria-label={t('chordDictionary.openDictionarySettings')}
        >
          <Icon name="settings" />
        </button>
      </div>
      <dialog open={settingsOpen} className="modal modal-bottom sm:modal-middle">
        <div className="modal-box max-w-4xl">
          <form method="dialog">
            <button
              type="submit"
              className="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
              onClick={handleSettingsClosed}
            >
              ✕
            </button>
          </form>
          <ChordDictionarySettings />
        </div>
      </dialog>
    </>
  );
};

ChordDictionaryToolbar.defaultProps = {
  disableUpdate: false,
};

export default ChordDictionaryToolbar;
