// src/renderer/views/ChordDictionary/ChordDictionaryChromaMenu.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Note } from 'tonal';

import {
  KeySignatureConfig,
  NOTE_NAMES,
  formatSharpsFlats,
  getNoteInKeySignature,
} from 'renderer/helpers';

type Props = {
  keySignature: KeySignatureConfig;
  selected: number | null;
  onSelect: (chroma: number) => void;
  filterChordsInKey: boolean;
};

const ChordDictionaryChromaMenu: React.FC<Props> = ({
  keySignature,
  selected,
  onSelect,
  filterChordsInKey,
}) => {
  const { t } = useTranslation();

  return (
    <div
      className="flex flex-col gap-2 p-3"
      role="tablist"
      aria-label={t('chordDictionary.chromaNavigation')}
    >
      {(filterChordsInKey ? keySignature.scale : NOTE_NAMES).map((note) => {
        const chroma = Note.chroma(note) as number;
        const isSelected = selected === chroma;

        return (
          <button
            key={note}
            type="button"
            className={`btn btn-ghost btn-block rounded-md p-2 px-4 mb-1 transition-colors duration-150 hover:bg-white/10 ${
              isSelected ? 'bg-primary-500 text-white shadow-md' : ''
            }`}
            role="tab"
            aria-selected={isSelected}
            onClick={() => onSelect(chroma)}
          >
            <span className="font-medium">
              {formatSharpsFlats(getNoteInKeySignature(note, keySignature.notes))}
            </span>
          </button>
        );
      })}
    </div>
  );
};

export default ChordDictionaryChromaMenu;

// src/views/ChordDictionary/ChordDictionaryChromaMenu.vue
<template>
  <div class="chord-dictionary-chroma-menu p-4 h-full">
    <ul
      class="menu bg-base-100"
      role="tablist"
      :aria-label="t('chordDictionary.chromaNavigation')"
    >
      <li v-for="note in notesList" :key="note">
        <a
          class="rounded-lg"
          role="tab"
          :aria-selected="selected === getChroma(note)"
          :class="{
            'bg-primary text-primary-content': selected === getChroma(note),
          }"
          @click="handleSelect(note)"
        >
          {{ formatNote(note) }}
        </a>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { Note } from "tonal";
import { useI18n } from "vue-i18n";
import type { KeySignatureConfig } from "@/helpers";
import {
  NOTE_NAMES,
  formatSharpsFlats,
  getNoteInKeySignature,
} from "@/helpers";

interface Props {
  keySignature: KeySignatureConfig;
  selected: number | null;
  filterChordsInKey: boolean;
}

interface Emits {
  (e: "select", chroma: number): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const { t } = useI18n();

const notesList = computed(() => {
  return props.filterChordsInKey ? props.keySignature.scale : NOTE_NAMES;
});

function getChroma(note: string): number {
  return Note.chroma(note) as number;
}

function formatNote(note: string): string {
  return formatSharpsFlats(
    getNoteInKeySignature(note, props.keySignature.notes),
  );
}

function handleSelect(note: string) {
  const chroma = getChroma(note);
  emit("select", chroma);
}
</script>
