// src/renderer/components/ChordNameLink/ChordNameLink.tsx
import React, { useMemo } from 'react';

import { NavLink } from 'react-router-dom';
import { ChordNameLinkProps } from './types';

import { ChordName } from '../ChordName/ChordName';

export const ChordNameLink: React.FC<ChordNameLinkProps> = ({
  className,
  chord,
  dictionaryUrl,
  ...rest
}) => {
  const to = useMemo(
    () => (chord ? `${dictionaryUrl}${encodeURIComponent(chord.tonic + chord.aliases[0])}` : ''),
    [chord, dictionaryUrl]
  );

  if (!chord) return null;

  return (
    <NavLink className={`link [ --Link--primary_color:currentColor ] ${className ?? ''}`} to={to}>
      <ChordName chord={chord} {...rest} />
    </NavLink>
  );
};

ChordNameLink.defaultProps = {
  dictionaryUrl: '/chord-dictionary/',
};

export default ChordNameLink;

// src/components/ChordNameLink/ChordNameLink.vue
<template>
  <RouterLink
    v-if="chord"
    :to="to"
    class="chord-name-link link text-inherit no-underline hover:opacity-85 hover:underline"
  >
    <ChordName
      :chord="chord"
      :notation="notation"
      :hideRoot="hideRoot"
      :highlightAlterations="highlightAlterations"
      :latinSharpsFlats="latinSharpsFlats"
      :size="size"
    />
  </RouterLink>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { RouterLink } from "vue-router";
import { ChordName } from "@/components/ChordName/";
import type { Chord } from "@tonaljs/chord";
import type { ChordNameProps } from "@/components/ChordName/ChordName.vue";

export interface ChordNameLinkProps extends Partial<ChordNameProps> {
  chord: Chord | null;
  dictionaryUrl?: string;
  size?: "xl" | "6xl";
}

const props = withDefaults(defineProps<ChordNameLinkProps>(), {
  dictionaryUrl: "/chord-dictionary/",
  chord: null,
  notation: "preferred",
  hideRoot: false,
  highlightAlterations: false,
  latinSharpsFlats: undefined,
  size: "xl",
});

const to = computed(() => {
  if (!props.chord) return "";
  return `${props.dictionaryUrl}${encodeURIComponent(props.chord.tonic + props.chord.aliases[0])}`;
});
</script>
