// src/views/Settings/ChordDisplaySettings/ChordDisplayAddModal.vue
<template>
  <div
    v-if="open"
    class="fixed inset-0 z-modal flex items-center justify-center bg-black/50"
  >
    <div class="card bg-base-100 shadow-xl w-full max-w-sm rounded-xl">
      <div class="card-body p-6">
        <h2 class="card-title text-base font-bold">
          {{ t("settings.chordDisplaySettings.newModule") }}
        </h2>
        <div class="fieldset w-full py-4">
          <label class="label">
            <span class="fieldset-legend">{{ t("common.name") }}</span>
          </label>
          <input
            type="text"
            class="input input w-full rounded-lg"
            :class="errors.name ? 'input-error' : ''"
            :value="name"
            @input="name = ($event.target as HTMLInputElement).value"
          />
          <label v-if="errors.name" class="label">
            <span class="label text-error">{{ errors.name }}</span>
          </label>
        </div>
        <div class="card-actions justify-end">
          <button class="btn btn-ghost" @click="$emit('cancel')">
            {{ t("common.cancel") }}
          </button>
          <button class="btn btn-success" @click="handleSave">
            {{ t("common.add") }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import { FieldError } from "./utils";

const { t } = useI18n();

const props = defineProps<{
  open: boolean;
}>();

const emit = defineEmits<{
  cancel: [];
  save: [name: string];
}>();

const name = ref("");
const errors = ref<Record<string, string>>({});

watch(
  () => props.open,
  (val) => {
    if (!val) {
      name.value = "";
      errors.value = {};
    }
  },
);

const handleSave = () => {
  emit("save", name.value);
};

defineExpose({
  handleSaveError(err: unknown) {
    if (err instanceof FieldError) {
      // FieldError 携带 i18n key（如 cannotBeEmpty），在展示层翻译
      errors.value = Object.fromEntries(
        Object.entries(err.fields).map(([field, key]) => [
          field,
          t(`settings.chordDisplaySettings.${key}`),
        ]),
      );
    }
  },
});
</script>

// src/renderer/views/Settings/ChordDisplaySettings/ChordDisplayAddModal.tsx
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';

import { FieldError } from './utils';

type Props = {
  open: boolean;
  onCancel: () => void;
  onSave: (name: string) => Promise<unknown>;
};

const ChordDisplayAddModal: React.FC<Props> = ({ open, onCancel, onSave }) => {
  const [name, setName] = useState<string>('');
  const [errors, setErrors] = useState<Record<string, string>>({});
  const { t } = useTranslation();

  const handleSave = () => {
    return onSave(name)
      .then(() => setName(''))
      .catch((err) => (err instanceof FieldError ? setErrors(err.fields) : null));
  };

  return (
    <dialog className={`modal ${open ? 'modal-open' : ''}`} open={open}>
      <div className="modal-box modal-sm">
        <h3 className="font-bold text-lg">{t('settings.chordDisplaySettings.newModule')}</h3>
        <div className="modal-content py-4">
          <div className="form-control w-full">
            <label htmlFor="newModuleName" className="label">
              <span className="label-text">{t('common.name')}</span>
            </label>
            <input
              id="newModuleName"
              type="text"
              placeholder={t('common.name')}
              className={`input input-bordered w-full ${errors.name ? 'input-error' : ''}`}
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            {errors.name && (
              <label htmlFor="newModuleName" className="label">
                <span className="label-text-alt text-error">{errors.name}</span>
              </label>
            )}
          </div>
        </div>
        <div className="modal-action">
          <button type="button" className="btn btn-ghost" onClick={onCancel}>
            {t('common.cancel')}
          </button>
          <button type="button" className="btn btn-success" onClick={handleSave}>
            {t('common.add')}
          </button>
        </div>
      </div>
      <form method="dialog" className="modal-backdrop">
        <button type="button" onClick={onCancel}>
          close
        </button>
      </form>
    </dialog>
  );
};

export default ChordDisplayAddModal;
